import {env} from 'cloudflare:workers';
import {authorizedAdmin} from '../../admin-auth';
import {readCampus} from '../../campus-store';
import type {Event} from '../../data';

export const dynamic='force-dynamic';
const PREFIX='event-posters/';
function detectedType(bytes:Uint8Array){if(bytes.length>=3&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return'image/jpeg';if(bytes.length>=8&&[137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v))return'image/png';if(bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')return'image/webp';return null}
function validKey(key:string|null){return !!key&&/^event-posters\/[a-f0-9-]{36}$/.test(key)}
export async function POST(req:Request){if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin||!await authorizedAdmin())return Response.json({error:'Admin sign-in required.'},{status:403});if(Number(req.headers.get('content-length')||0)>10_500_000)return Response.json({error:'Poster must be under 10 MB.'},{status:413});try{const form=await req.formData(),file=form.get('file');if(!(file instanceof File)||file.size<1000||file.size>10_000_000)return Response.json({error:'Choose an image under 10 MB.'},{status:400});const bytes=new Uint8Array(await file.arrayBuffer());const type=detectedType(bytes);if(!type||type!==file.type)return Response.json({error:'Choose a JPEG, PNG or WebP image.'},{status:400});const key=PREFIX+crypto.randomUUID();await env.BUCKET!.put(key,bytes,{httpMetadata:{contentType:type}});return Response.json({url:`/api/event-poster?key=${encodeURIComponent(key)}`})}catch{return Response.json({error:'Could not upload poster. Please try again.'},{status:500})}}
export async function GET(req:Request){const key=new URL(req.url).searchParams.get('key');if(!validKey(key))return new Response('Not found',{status:404});try{const campus=await readCampus();const published=campus.events.some((e:Event)=>e.posterUrl===`/api/event-poster?key=${encodeURIComponent(key!)}`);if(!published&&!await authorizedAdmin())return new Response('Not found',{status:404,headers:{'Cache-Control':'no-store'}});const object=await env.BUCKET!.get(key!);if(!object)return new Response('Not found',{status:404,headers:{'Cache-Control':'no-store'}});return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'application/octet-stream','Cache-Control':published?'public,max-age=300':'private,no-store','X-Content-Type-Options':'nosniff'}})}catch{return new Response('Poster unavailable',{status:503,headers:{'Cache-Control':'no-store'}})}}
