import {env} from 'cloudflare:workers';
import {authorizedAdmin} from '../../admin-auth';
import {readCampus} from '../../campus-store';
import type {Event} from '../../data';

export const dynamic='force-dynamic';
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'no-store'}});
const sameOrigin=(req:Request)=>!req.headers.get('origin')||req.headers.get('origin')===new URL(req.url).origin;
async function table(){await env.DB!.prepare(`CREATE TABLE IF NOT EXISTS event_participations (id TEXT PRIMARY KEY, event_id TEXT NOT NULL, event_title TEXT NOT NULL, name TEXT NOT NULL, institution TEXT NOT NULL, email TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(event_id,email))`).run()}
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'Invalid origin.'},403);if(Number(req.headers.get('content-length')||0)>4000)return json({error:'Form is too large.'},413);try{const input=await req.json() as Record<string,unknown>;const eventId=String(input.eventId||'').trim(),name=String(input.name||'').trim(),institution=String(input.institution||'').trim(),email=String(input.email||'').trim().toLowerCase();if(!eventId||!name||name.length>100||!institution||institution.length>120||!email||email.length>180||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||input.consent!==true)return json({error:'Complete your details and consent to registration.'},400);const campus=await readCampus();const event=campus.events.find((e:Event)=>e.id===eventId);if(!event||!event.registrationOpen)return json({error:'Registration is not open for this event.'},409);if(event.endsAt&&Date.parse(event.endsAt)<Date.now())return json({error:'This event has ended.'},409);await table();const existing=await env.DB!.prepare('SELECT id FROM event_participations WHERE event_id=? AND email=?').bind(eventId,email).first<{id:string}>();if(existing)return json({id:existing.id,status:'already_registered'},200);const id=crypto.randomUUID();await env.DB!.prepare('INSERT INTO event_participations (id,event_id,event_title,name,institution,email,status,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,event.id,event.title,name,institution,email,'registered',new Date().toISOString()).run();return json({id,status:'registered'},201)}catch{return json({error:'Could not complete registration. Please try again.'},500)}}
export async function GET(){if(!await authorizedAdmin())return json({error:'Admin sign-in required.'},403);try{await table();const result=await env.DB!.prepare('SELECT id,event_id AS eventId,event_title AS eventTitle,name,institution,email,status,created_at AS createdAt FROM event_participations ORDER BY created_at DESC LIMIT 500').all();return json(result.results)}catch{return json({error:'Could not load participants.'},500)}}
export async function PATCH(req:Request){if(!sameOrigin(req)||!await authorizedAdmin())return json({error:'Admin sign-in required.'},403);try{const input=await req.json() as Record<string,unknown>;const id=String(input.id||''),name=String(input.name||'').trim(),institution=String(input.institution||'').trim(),email=String(input.email||'').trim().toLowerCase(),status=String(input.status||'');if(!id||!name||name.length>100||!institution||institution.length>120||!email||email.length>180||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!['registered','checked_in','cancelled'].includes(status))return json({error:'Invalid participant details.'},400);await table();const result=await env.DB!.prepare('UPDATE event_participations SET name=?,institution=?,email=?,status=? WHERE id=?').bind(name,institution,email,status,id).run();return Number(result.meta.changes)?json({ok:true}):json({error:'Participant not found.'},404)}catch{return json({error:'Could not update participant. Check whether this email is already registered.'},500)}}
export async function DELETE(req:Request){if(!sameOrigin(req)||!await authorizedAdmin())return json({error:'Admin sign-in required.'},403);const id=new URL(req.url).searchParams.get('id');if(!id)return json({error:'Missing participant ID.'},400);try{await table();await env.DB!.prepare('DELETE FROM event_participations WHERE id=?').bind(id).run();return json({ok:true})}catch{return json({error:'Could not remove participant.'},500)}}
