'use client';
import {t,type Lang} from './i18n';
import {useEffect,useRef,useState} from 'react';
import {Camera,Plus,Trash2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {IScannerControls} from '@zxing/browser';
import IdReview from './id-review';
type Visitor={id:string;name:string;institution:string;badgeCode:string;eventName:string;createdAt:string};
export default function BadgeDesk({events,lang}:{lang:Lang;events:{id:string;title:string}[]}){const [items,setItems]=useState<Visitor[]>([]),[form,setForm]=useState({name:'',institution:'',badgeCode:'',eventName:''}),[error,setError]=useState(''),[scanning,setScanning]=useState(false);const video=useRef<HTMLVideoElement>(null),controls=useRef<IScannerControls|null>(null),requested=useRef(false);
 useEffect(()=>{fetch('/api/visitors').then(async r=>{const b=await r.json() as Visitor[] & {error?:string};if(r.ok)setItems(b);else setError(b.error||"Could not load visitors.")}).catch(()=>setError('Could not load visitor records.'));return stop},[]);
 function stop(){requested.current=false;controls.current?.stop();controls.current=null;setScanning(false)}
 async function scan(){if(requested.current)return;setError('');requested.current=true;setScanning(true);try{if(!navigator.mediaDevices?.getUserMedia||!video.current)throw Error('Camera unavailable. Enter the badge code manually.');const {BrowserMultiFormatReader}=await import('@zxing/browser');if(!requested.current)return;const handle=await new BrowserMultiFormatReader().decodeFromConstraints({video:{facingMode:{ideal:'environment'}}},video.current,result=>{if(result){setForm(f=>({...f,badgeCode:result.getText().slice(0,160)}));stop()}});if(requested.current)controls.current=handle;else handle.stop()}catch(e:any){stop();setError(e?.name==='NotAllowedError'?'Camera permission denied. Enable it in your browser settings.':e?.message||'Could not open camera.')}}
 async function add(e:React.FormEvent){e.preventDefault();setError('');try{const res=await fetch('/api/visitors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const body=await res.json() as Visitor & {error?:string};if(!res.ok)throw Error(body.error);setItems(v=>[body,...v]);setForm({name:'',institution:'',badgeCode:'',eventName:''})}catch(e:any){setError(e.message||'Could not save visitor.')}}
 async function remove(id:string){const res=await fetch('/api/visitors?id='+encodeURIComponent(id),{method:'DELETE'});if(res.ok)setItems(v=>v.filter(x=>x.id!==id));else setError('Could not remove record.')}
 return <div className="badge-desk"><IdReview lang={lang}/><p className="help-text">{t(lang,"Scan an event badge barcode or QR code, then enter the visitor's details. The badge code is separate from the campus location code. Do not scan government identity documents.")}</p><form onSubmit={add} className="badge-form"><label>{t(lang,"Visitor name")}<input required value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label><label>College / organisation<input value={form.institution} onChange={e=>setForm(f=>({...f,institution:e.target.value}))}/></label><label>{t(lang,"Event badge code")}<div className="badge-code"><input required value={form.badgeCode} onChange={e=>setForm(f=>({...f,badgeCode:e.target.value}))}/><Button type="button" variant="outline" onClick={scanning?stop:scan}>{scanning?<X size={17}/>:<Camera size={17}/>} {t(lang,scanning?'Stop':'Scan')}</Button></div></label><label>Event<select value={form.eventName} onChange={e=>setForm(f=>({...f,eventName:e.target.value}))}><option value="">General visit</option>{events.map(event=><option key={event.id} value={event.title}>{event.title}</option>)}</select></label><video className="scanner-video" ref={video} autoPlay muted playsInline style={{display:scanning?'block':'none'}}/><Button type="submit"><Plus size={17}/>{t(lang,"Add visitor")}</Button></form>{error&&<p className="login-error" role="alert">{t(lang,error)}</p>}<div className="badge-list-head"><h3>{t(lang,"Recent badge check-ins")}</h3><span>{items.length} {t(lang,'records')}</span></div>{items.length?items.map(v=><div className="badge-record" key={v.id}><div><strong>{v.name}</strong><small>{v.institution||t(lang,'Visitor')} · {v.eventName||t(lang,'General visit')} · {new Date(v.createdAt).toLocaleString()}</small><code>{v.badgeCode}</code></div><button onClick={()=>remove(v.id)} aria-label={'Remove '+v.name}><Trash2 size={17}/></button></div>):<p className="empty-state">{t(lang,"No visitors checked in yet.")}</p>}</div>
}
