'use client';
import {t,type Lang} from './i18n';
import {useEffect,useState} from 'react';
import {Camera,CheckCircle2,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
function PhotoField({label,file,onChange,lang}:{lang:Lang;label:string;file:File|null;onChange:(file:File|null)=>void}){const [preview,setPreview]=useState('');useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);return <div className="id-photo-field"><strong>{label}</strong><span>{file?.name||t(lang,'Take a photo or choose an image')}</span>{preview&&<img src={preview} alt={`${label} preview`}/>}<div className="id-photo-actions"><label>{t(lang,"Take photo")}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>onChange(e.target.files?.[0]||null)}/></label><label>{t(lang,"Choose file")}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>onChange(e.target.files?.[0]||null)}/></label></div><small>{t(lang,"JPEG, PNG or WebP · up to 10 MB")}</small></div>}
export default function IdCheckin({events,onClose,lang}:{lang:Lang;events:{id:string;title:string}[];onClose:()=>void}){const [name,setName]=useState(''),[institution,setInstitution]=useState(''),[eventName,setEventName]=useState(''),[front,setFront]=useState<File|null>(null),[back,setBack]=useState<File|null>(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[received,setReceived]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!front||!back||!consent){setError('Both sides and consent are required.');return}if(front.size>10_000_000||back.size>10_000_000){setError('Each photo must be under 10 MB.');return}setBusy(true);try{const form=new FormData();form.append('name',name);form.append('institution',institution);form.append('eventName',eventName);form.append('front',front);form.append('back',back);form.append('consent','yes');const response=await fetch('/api/id-checkins',{method:'POST',body:form});const body=await response.json() as {error?:string};if(!response.ok)throw Error(body.error||'Upload failed.');setReceived(true);setFront(null);setBack(null)}catch(err:any){setError(err.message||'Upload failed.')}finally{setBusy(false)}}
 return <div className="modal-backdrop id-backdrop" onClick={onClose}><div className="id-modal" role="dialog" aria-modal="true" aria-label={t(lang,'Visitor ID check-in')} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="section-kicker">{t(lang,"VISITOR CHECK-IN")}</span><h2>{t(lang,"Submit your college ID")}</h2></div><button onClick={onClose} aria-label={t(lang,'Close')}><X/></button></div>{received?<div className="id-success"><CheckCircle2 size={38}/><h3>{t(lang,"Photos received")}</h3><p>{t(lang,"Project administrators can review both sides in the admin portal. Show your physical ID at the desk if requested.")}</p><Button onClick={onClose}>{t(lang,"Done")}</Button></div>:<form onSubmit={submit} className="id-form"><p>{t(lang,"This is a personal project, not an official KPRIET check-in. Submit only a college or event ID when requested. Do not upload Aadhaar, passport, driving licence or other government ID.")}</p><div className="id-fields"><label>{t(lang,"Your name")}<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label>{t(lang,"College / organisation")}<input maxLength={100} value={institution} onChange={e=>setInstitution(e.target.value)}/></label></div><label>{t(lang,"Event")}<select value={eventName} onChange={e=>setEventName(e.target.value)}><option value="">{t(lang,"General visit")}</option>{events.map(event=><option key={event.id} value={event.title}>{event.title}</option>)}</select></label><div className="id-photo-grid"><PhotoField lang={lang} label={t(lang,"Front of ID")} file={front} onChange={setFront}/><PhotoField lang={lang} label={t(lang,"Back of ID")} file={back} onChange={setBack}/></div><label className="id-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span>{t(lang,"I agree to send both ID photos to the KPR Compass project administrators for event check-in. They can view and delete them in the protected admin portal.")}</span></label>{error&&<div className="login-error" role="alert">{t(lang,error)}</div>}<Button type="submit" className="wide" disabled={busy}><Camera size={17}/>{t(lang,busy?'Uploading…':'Submit both sides')}</Button></form>}</div></div>
}
