'use client';
import {t,type Lang} from './i18n';
import {useEffect,useState} from 'react';
import {Check,RefreshCw,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
type Submission={id:string;name:string;institution:string;eventName:string;status:'new'|'reviewed';createdAt:string};
export default function IdReview({lang}:{lang:Lang}){const [items,setItems]=useState<Submission[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const res=await fetch('/api/id-checkins',{cache:'no-store'});const body=await res.json() as Submission[] & {error?:string};if(!res.ok)throw Error(body.error||'Could not load submissions.');setItems(body)}catch(e:any){setError(e.message||'Could not load submissions.')}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);
 async function review(item:Submission){const res=await fetch('/api/id-checkins',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status:item.status==='new'?'reviewed':'new'})});if(res.ok)setItems(list=>list.map(v=>v.id===item.id?{...v,status:v.status==='new'?'reviewed':'new'}:v));else setError('Could not update review status.')}
 async function remove(item:Submission){if(!confirm(lang==='ta'?`${item.name} அட்டையின் இரு படங்களையும் நிரந்தரமாக நீக்கவா?`:`Delete both ID photos for ${item.name}? This cannot be undone.`))return;const res=await fetch('/api/id-checkins?id='+encodeURIComponent(item.id),{method:'DELETE'});if(res.ok)setItems(list=>list.filter(v=>v.id!==item.id));else setError('Could not delete ID photos.')}
 return <section className="id-review"><div className="badge-list-head"><div><h3>{t(lang,"Submitted college IDs")}</h3><p className="help-text">{t(lang,"Front and back images are private to authorized staff. Delete them when check-in is complete.")}</p></div><Button type="button" variant="outline" onClick={load} disabled={busy}><RefreshCw size={16}/>Refresh</Button></div>{error&&<p className="login-error" role="alert">{t(lang,error)}</p>}{items.length?items.map(item=><article className="id-review-card" key={item.id}><div className="id-review-heading"><div><strong>{item.name}</strong><small>{item.institution||t(lang,'Visitor')} · {item.eventName||t(lang,'General visit')} · {new Date(item.createdAt).toLocaleString()}</small></div><span className={item.status==='reviewed'?'reviewed':'pending'}>{t(lang,item.status)}</span></div><div className="id-review-images"><a href={`/api/id-checkins/image?id=${encodeURIComponent(item.id)}&side=front`} target="_blank" rel="noreferrer"><img src={`/api/id-checkins/image?id=${encodeURIComponent(item.id)}&side=front`} alt={`Front of ${item.name}'s college ID`}/><span>{t(lang,"Front · open")}</span></a><a href={`/api/id-checkins/image?id=${encodeURIComponent(item.id)}&side=back`} target="_blank" rel="noreferrer"><img src={`/api/id-checkins/image?id=${encodeURIComponent(item.id)}&side=back`} alt={`Back of ${item.name}'s college ID`}/><span>{t(lang,"Back · open")}</span></a></div><div className="id-review-actions"><Button type="button" variant="outline" onClick={()=>review(item)}><Check size={16}/>{t(lang,item.status==='new'?'Mark reviewed':'Mark new')}</Button><button onClick={()=>remove(item)}><Trash2 size={16}/>{t(lang,"Delete photos")}</button></div></article>):<p className="empty-state">{t(lang,"No ID photos submitted yet.")}</p>}</section>
}
