import {env} from 'cloudflare:workers';
import {authorizedAdmin} from '../../admin-auth';
export const dynamic='force-dynamic';
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
const sameOrigin=(req:Request)=>{const origin=req.headers.get('origin');return !origin||origin===new URL(req.url).origin};
async function table(){await env.DB!.prepare('CREATE TABLE IF NOT EXISTS id_checkins (id TEXT PRIMARY KEY, name TEXT NOT NULL, institution TEXT NOT NULL, event_name TEXT NOT NULL, front_key TEXT NOT NULL, back_key TEXT NOT NULL, status TEXT NOT NULL DEFAULT \'new\', created_at TEXT NOT NULL)').run();await env.DB!.prepare('CREATE TABLE IF NOT EXISTS id_upload_quota (key TEXT PRIMARY KEY, count INTEGER NOT NULL)').run()}
function imageType(bytes:Uint8Array){if(bytes.length>=3&&bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return 'image/jpeg';if(bytes.length>=8&&[137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v))return 'image/png';if(bytes.length>=12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')return 'image/webp';return null}
async function photo(value:FormDataEntryValue|null){if(!(value instanceof File)||value.size<1000||value.size>10_000_000)return null;const bytes=new Uint8Array(await value.arrayBuffer());const type=imageType(bytes);return type&&type===value.type?{bytes,type}:null}
async function quota(req:Request){const ip=req.headers.get('cf-connecting-ip')||'local';const secret=(env as unknown as {ADMIN_SESSION_SECRET?:string}).ADMIN_SESSION_SECRET;if(!secret)throw Error('Upload configuration missing');const hour=new Date().toISOString().slice(0,13);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${ip}:${hour}`)));const token=Array.from(digest).map(n=>n.toString(16).padStart(2,'0')).join('');const result=await env.DB!.prepare('INSERT INTO id_upload_quota(key,count) VALUES (?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 WHERE count<60').bind(token).run();return Number(result.meta.changes)>0}
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'Invalid origin.'},403);if(Number(req.headers.get('content-length')||0)>20_500_000)return json({error:'Images must be under 10 MB each.'},413);let keys:string[]=[];try{const form=await req.formData();const name=String(form.get('name')||'').trim(),institution=String(form.get('institution')||'').trim(),eventName=String(form.get('eventName')||'').trim();if(!name||name.length>100||institution.length>100||eventName.length>100||form.get('consent')!=='yes')return json({error:'Enter your name and confirm consent.'},400);const front=await photo(form.get('front')),back=await photo(form.get('back'));if(!front||!back)return json({error:'Add both sides as JPEG, PNG or WebP images under 10 MB each.'},400);await table();if(!await quota(req))return json({error:'Too many submissions from this connection. Ask the help desk for assistance.'},429);const id=crypto.randomUUID();keys=[`visitor-ids/${id}/front`,`visitor-ids/${id}/back`];await env.BUCKET!.put(keys[0],front.bytes,{httpMetadata:{contentType:front.type}});await env.BUCKET!.put(keys[1],back.bytes,{httpMetadata:{contentType:back.type}});await env.DB!.prepare('INSERT INTO id_checkins(id,name,institution,event_name,front_key,back_key,status,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,name,institution,eventName,keys[0],keys[1],'new',new Date().toISOString()).run();return json({id,status:'received'},201)}catch(error){console.error('ID upload failed:',error instanceof Error?error.name:'unknown error');if(keys.length)await Promise.allSettled(keys.map(key=>env.BUCKET!.delete(key)));return json({error:'Could not upload the ID photos. Please try again.'},500)}}
export async function GET(){if(!await authorizedAdmin())return json({error:'Admin sign-in required.'},403);try{await table();const rows=await env.DB!.prepare('SELECT id,name,institution,event_name AS eventName,status,created_at AS createdAt FROM id_checkins ORDER BY created_at DESC LIMIT 100').all();return json(rows.results)}catch{return json({error:'Could not load ID submissions.'},500)}}
export async function PATCH(req:Request){if(!sameOrigin(req)||!await authorizedAdmin())return json({error:'Admin sign-in required.'},403);try{const {id,status}=await req.json() as {id?:string;status?:string};if(!id||!['new','reviewed'].includes(status||''))return json({error:'Invalid review status.'},400);await table();await env.DB!.prepare('UPDATE id_checkins SET status=? WHERE id=?').bind(status,id).run();return json({ok:true})}catch{return json({error:'Could not update submission.'},500)}}
export async function DELETE(req:Request){if(!sameOrigin(req)||!await authorizedAdmin())return json({error:'Admin sign-in required.'},403);const id=new URL(req.url).searchParams.get('id');if(!id)return json({error:'Missing ID.'},400);try{await table();const row=await env.DB!.prepare('SELECT front_key AS frontKey,back_key AS backKey FROM id_checkins WHERE id=?').bind(id).first<{frontKey:string;backKey:string}>();if(!row)return json({error:'Submission not found.'},404);await Promise.all([env.BUCKET!.delete(row.frontKey),env.BUCKET!.delete(row.backKey)]);await env.DB!.prepare('DELETE FROM id_checkins WHERE id=?').bind(id).run();return json({ok:true})}catch{return json({error:'Could not delete submission.'},500)}}
